"use client";
import { useState } from "react";
import { Loader2, Pencil, Users } from "lucide-react";
import { toast } from "sonner";
import { useRecordSexComposition, useSexComposition } from "@/hooks/use-operations";
import { ApiError } from "@/lib/api-client";
import { todayIso } from "@/lib/format";
import type { Batch } from "@/lib/types";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export function SexCompositionCard({ batch }: { batch: Batch }) {
  const { data: current } = useSexComposition(batch.id); const save = useRecordSexComposition();
  const [editing, setEditing] = useState(false); const [date, setDate] = useState(todayIso()); const [male, setMale] = useState(""); const [female, setFemale] = useState(""); const [unknown, setUnknown] = useState(""); const [reason, setReason] = useState(""); const [error, setError] = useState("");
  function startEdit() { setEditing(true); setDate(current?.observedOn ?? todayIso()); setMale(String(current?.maleCount ?? "")); setFemale(String(current?.femaleCount ?? "")); setUnknown(String(current?.unclassifiedCount ?? batch.currentPopulation)); setReason(""); setError(""); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); const values = [male, female, unknown].map(Number); const total = values.reduce((sum, value) => sum + (Number.isFinite(value) ? value : 0), 0); if (values.some((value) => !Number.isInteger(value) || value < 0)) return setError("Use whole numbers only."); if (total !== batch.currentPopulation) return setError(`The counts must equal ${batch.currentPopulation} birds.`); try { const result = await save.mutateAsync({ batchId: batch.id, body: { observedOn: date, maleCount: values[0], femaleCount: values[1], unclassifiedCount: values[2], revisionReason: reason || null } }); toast.success("queued" in result && result.queued ? "Sex composition saved locally; waiting to sync." : "Sex composition saved."); setEditing(false); } catch (err) { setError(err instanceof ApiError ? err.message : "Could not save the sex count."); } }
  return <section className="rounded-xl border bg-card px-3 py-2.5"><div className="flex items-center justify-between gap-2"><h2 className="flex items-center gap-2 text-sm font-bold"><Users className="size-4 text-primary" /> Sex composition</h2><Badge variant="outline" className="text-[10px]">Whole batch</Badge></div>{!editing ? <div className="mt-2 flex flex-wrap items-center gap-2">{current ? <div className="grid min-w-0 flex-1 grid-cols-3 gap-1.5 text-center"><Stat label="Male" value={current.maleCount} /><Stat label="Female" value={current.femaleCount} /><Stat label="Unclassified" value={current.unclassifiedCount} /></div> : <p className="min-w-0 flex-1 text-xs text-muted-foreground">No count yet. Record after sexing.</p>}{current && <span className="w-full text-[11px] text-muted-foreground">Checked {current.observedOn} · total {current.populationAsOfObservation}{current.pendingSync ? " · Pending sync" : ""}</span>}<Button variant="outline" className="h-9 shrink-0 px-3 text-xs" onClick={startEdit}><Pencil className="size-3.5" />{current ? "Correct" : "Record"}</Button></div> : <form onSubmit={submit} className="mt-3 space-y-3"><p className="text-xs text-muted-foreground">Unclassified keeps the total honest when sexing is uncertain.</p><div className="grid grid-cols-3 gap-2"><CountInput id={`male-${batch.id}`} label="Male" value={male} onChange={setMale} /><CountInput id={`female-${batch.id}`} label="Female" value={female} onChange={setFemale} /><CountInput id={`unknown-${batch.id}`} label="Unclassified" value={unknown} onChange={setUnknown} /></div><div className="space-y-1"><Label htmlFor={`sex-date-${batch.id}`}>Observed on</Label><Input id={`sex-date-${batch.id}`} type="date" max={todayIso()} value={date} onChange={(event) => setDate(event.target.value)} /></div>{current && <div className="space-y-1"><Label htmlFor={`sex-reason-${batch.id}`}>Why corrected? <span className="font-normal text-muted-foreground">optional</span></Label><Input id={`sex-reason-${batch.id}`} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Rechecked the flock" /></div>}{error && <p role="alert" className="rounded-lg border border-destructive/30 bg-destructive/5 px-3 py-2 text-sm text-destructive">{error}</p>}<div className="flex gap-2"><Button type="button" variant="outline" className="h-9 flex-1" onClick={() => setEditing(false)}>Cancel</Button><Button type="submit" className="h-9 flex-1" disabled={save.isPending}>{save.isPending && <Loader2 className="animate-spin" />}Save</Button></div></form>}</section>;
}
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-md bg-muted/40 px-2 py-1.5"><p className="text-[9px] font-semibold uppercase text-muted-foreground">{label}</p><p className="text-base font-bold tabular-nums">{value}</p></div>; }
function CountInput({ id, label, value, onChange }: { id: string; label: string; value: string; onChange: (value: string) => void }) { return <div className="space-y-1"><Label htmlFor={id} className="text-xs">{label}</Label><Input id={id} type="number" min="0" step="1" inputMode="numeric" value={value} onChange={(event) => onChange(event.target.value)} className="h-10 text-center text-base font-semibold" /></div>; }
