export type Language = "en" | "taglish";

export const LANGUAGE_LABELS: Record<Language, string> = {
  en: "English",
  taglish: "Taglish",
};

export const messages = {
  en: {
    "common.save": "Save", "common.cancel": "Cancel", "common.back": "Back", "common.loading": "Loading…", "common.retry": "Try again", "common.noRecords": "No records yet", "common.optional": "optional", "common.required": "required", "common.batch": "Batch", "common.date": "Date", "common.notes": "Notes", "common.farmWide": "Farm-wide", "common.when": "When", "common.type": "Type", "common.quantity": "Quantity", "common.unit": "Unit", "common.purpose": "Purpose", "common.description": "Description", "common.optionalDetails": "Optional details", "common.recorded": "Recorded", "common.shown": "shown",
    "nav.home": "Home", "nav.alerts": "Alerts", "nav.incubation": "Incubation", "nav.tasks": "Tasks", "nav.products": "Products used", "nav.analytics": "Farm summary", "nav.finance": "Finance", "nav.settings": "Settings", "nav.more": "More", "nav.record": "Record", "role.manager": "Farm manager", "role.handler": "Handler",
    "dashboard.todayTasks": "Today’s tasks", "dashboard.activeBatches": "Active batches", "dashboard.searchPlaceholder": "Search batches", "dashboard.allStages": "All stages", "dashboard.viewBatch": "View batch", "dashboard.logNow": "Log now", "dashboard.birdsAlive": "Birds alive", "dashboard.populationChanges": "Population changes", "dashboard.currentStage": "Current stage", "dashboard.ageReference": "Age reference", "dashboard.autoStage": "Stage based on age",
    "dashboard.goodMorning": "Good morning", "dashboard.goodAfternoon": "Good afternoon", "dashboard.goodEvening": "Good evening", "dashboard.activeBatch": "active batch", "dashboard.activeBatchesPlural": "active batches", "dashboard.todayTasksHint": "Finish the urgent task first.", "dashboard.viewAllTasks": "View all tasks", "dashboard.loadingBatches": "Loading batches…", "dashboard.createBatch": "New batch", "dashboard.noBatches": "No batches yet",
    "record.title": "Record activity", "record.choose": "Choose what happened", "record.populationChange": "Bird count change", "record.sickness": "Health concern", "record.product": "Feed or medicine used", "record.behavior": "Behavior observed", "record.optionalMeasurements": "Optional measurements", "record.measurementHint": "Temperature, feed, or water only when measured", "record.addMeasurement": "Add measurement", "record.open": "Open",
    "tasks.title": "Farm tasks", "tasks.late": "Late", "tasks.today": "Today", "tasks.next": "Next", "tasks.done": "Done", "tasks.assign": "Assign task", "tasks.anyHandler": "Any handler", "tasks.farmWide": "Farm-wide task", "tasks.start": "Start", "tasks.markDone": "Done", "tasks.what": "What needs to be done?", "tasks.instructions": "Instructions", "tasks.who": "Who can do it?", "tasks.whichBatch": "Which batch?", "tasks.due": "Due date and time", "tasks.priority": "Priority", "tasks.allTasks": "All farm tasks", "tasks.myTasks": "My tasks", "tasks.open": "open", "tasks.overdue": "Overdue", "tasks.noDue": "No due date",
    "inputs.title": "Products used", "inputs.description": "Record feed, vitamins, medicine, or vaccines by batch.", "inputs.record": "Record product", "inputs.recent": "Recent products", "inputs.brand": "Brand or product", "inputs.variant": "Variant or supplier", "inputs.usedAt": "When was it used?", "inputs.noMeasure": "Leave quantity blank if it was not measured.", "inputs.history": "Recent product records",
    "finance.title": "Farm finance", "finance.income": "Income", "finance.expenses": "Expenses", "finance.net": "Net cash recorded", "finance.record": "Record expense or income", "finance.batchHint": "Choose the batch first.", "finance.notAccounting": "Simple farm ledger only.", "finance.where": "Where should this be recorded?", "finance.category": "Category", "finance.amount": "Amount (PHP)", "finance.history": "Recorded transactions",
    "incubation.title": "Incubation", "incubation.loadEggs": "Load eggs", "incubation.hatchResult": "Record hatch result", "incubation.recordLoad": "Record an egg load", "incubation.loadReference": "Load reference", "incubation.incubator": "Incubator", "incubation.dateLoaded": "Date loaded", "incubation.eggsLoaded": "How many eggs were loaded?", "incubation.requiredFields": "Required fields", "incubation.optionalDetails": "Optional details", "incubation.expectedDate": "Expected hatch date", "incubation.eggSource": "Egg source", "incubation.bloodline": "Bloodline", "incubation.recordedLoads": "Recorded loads", "incubation.eggs": "eggs loaded", "incubation.hatched": "hatched", "incubation.hatchRate": "hatch rate", "incubation.actualDate": "Actual hatch date", "incubation.unhatched": "Unhatched", "incubation.removed": "Removed or damaged", "incubation.accounted": "eggs accounted for", "incubation.saveResults": "Save hatch results", "incubation.createBatch": "Create batch from hatch",
    "settings.title": "Settings", "settings.preferences": "Language and appearance", "settings.language": "Language", "settings.appearance": "Appearance", "settings.light": "Light", "settings.dark": "Dark", "settings.preferencesDescription": "Choose the language and screen style you prefer.",
    "status.validation": "Validation workspace", "status.synthetic": "Synthetic data only",
  },
  taglish: {
    "common.save": "I-save", "common.cancel": "Cancel", "common.back": "Bumalik", "common.loading": "Naglo-load…", "common.retry": "Subukan ulit", "common.noRecords": "Wala pang record", "common.optional": "optional", "common.required": "kailangan", "common.batch": "Batch", "common.date": "Petsa", "common.notes": "Notes", "common.farmWide": "Buong farm", "common.when": "Kailan", "common.type": "Uri", "common.quantity": "Dami", "common.unit": "Unit", "common.purpose": "Para saan", "common.description": "Description", "common.optionalDetails": "Optional na detalye", "common.recorded": "Na-record", "common.shown": "nakita",
    "nav.home": "Home", "nav.alerts": "Alerts", "nav.incubation": "Incubation", "nav.tasks": "Gawain", "nav.products": "Mga ginamit", "nav.analytics": "Farm summary", "nav.finance": "Finance", "nav.settings": "Settings", "nav.more": "Iba pa", "nav.record": "Record", "role.manager": "Manager ng farm", "role.handler": "Handler",
    "dashboard.todayTasks": "Gawain ngayon", "dashboard.activeBatches": "Active batches", "dashboard.searchPlaceholder": "Maghanap ng batch", "dashboard.allStages": "Lahat ng stage", "dashboard.viewBatch": "Tingnan ang batch", "dashboard.logNow": "Mag-record", "dashboard.birdsAlive": "Buhay na manok", "dashboard.populationChanges": "Pagbabago sa bilang", "dashboard.currentStage": "Current stage", "dashboard.ageReference": "Edad ng batch", "dashboard.autoStage": "Base sa edad ang stage",
    "dashboard.goodMorning": "Magandang umaga", "dashboard.goodAfternoon": "Magandang hapon", "dashboard.goodEvening": "Magandang gabi", "dashboard.activeBatch": "active batch", "dashboard.activeBatchesPlural": "active batches", "dashboard.todayTasksHint": "Unahin ang urgent na gawain.", "dashboard.viewAllTasks": "Tingnan lahat ng gawain", "dashboard.loadingBatches": "Naglo-load ng batches…", "dashboard.createBatch": "Bagong batch", "dashboard.noBatches": "Wala pang batch",
    "record.title": "Mag-record ng nangyari", "record.choose": "Ano ang nangyari?", "record.populationChange": "Pagbabago sa bilang", "record.sickness": "May sakit o sintomas", "record.product": "Feed, vitamins, o gamot", "record.behavior": "Napansing behavior", "record.optionalMeasurements": "Optional na sukat", "record.measurementHint": "Temperature, feed, o water kapag nasukat", "record.addMeasurement": "Magdagdag ng sukat", "record.open": "Buksan",
    "tasks.title": "Mga gawain sa farm", "tasks.late": "Late", "tasks.today": "Ngayon", "tasks.next": "Susunod", "tasks.done": "Tapos", "tasks.assign": "Mag-assign ng gawain", "tasks.anyHandler": "Kahit sinong handler", "tasks.farmWide": "Gawain para sa buong farm", "tasks.start": "Simulan", "tasks.markDone": "Tapos na", "tasks.what": "Anong gagawin?", "tasks.instructions": "Instructions", "tasks.who": "Sino ang gagawa?", "tasks.whichBatch": "Aling batch?", "tasks.due": "Deadline", "tasks.priority": "Priority", "tasks.allTasks": "Lahat ng gawain", "tasks.myTasks": "Mga gawain ko", "tasks.open": "bukas", "tasks.overdue": "Late", "tasks.noDue": "Walang deadline",
    "inputs.title": "Mga ginamit", "inputs.description": "I-record ang feed, vitamins, gamot, o vaccine per batch.", "inputs.record": "I-record ang ginamit", "inputs.recent": "Mga huling ginamit", "inputs.brand": "Brand o product", "inputs.variant": "Variant o supplier", "inputs.usedAt": "Kailan ginamit?", "inputs.noMeasure": "Iwanang blank ang dami kung hindi nasukat.", "inputs.history": "Mga huling product record",
    "finance.title": "Finance ng farm", "finance.income": "Kita", "finance.expenses": "Gastos", "finance.net": "Net cash na na-record", "finance.record": "Mag-record ng gastos o kita", "finance.batchHint": "Piliin muna ang batch.", "finance.notAccounting": "Simple farm ledger lang.", "finance.where": "Saan ito ire-record?", "finance.category": "Category", "finance.amount": "Amount (PHP)", "finance.history": "Mga na-record na transaction",
    "incubation.title": "Incubation", "incubation.loadEggs": "Mag-load ng itlog", "incubation.hatchResult": "I-record ang hatch result", "incubation.recordLoad": "I-record ang load ng itlog", "incubation.loadReference": "Pangalan ng load", "incubation.incubator": "Incubator", "incubation.dateLoaded": "Petsa ng load", "incubation.eggsLoaded": "Ilang itlog ang ni-load?", "incubation.requiredFields": "Required fields", "incubation.optionalDetails": "Optional na detalye", "incubation.expectedDate": "Expected hatch date", "incubation.eggSource": "Source ng itlog", "incubation.bloodline": "Bloodline", "incubation.recordedLoads": "Mga na-record na load", "incubation.eggs": "itlog na ni-load", "incubation.hatched": "napisa", "incubation.hatchRate": "hatch rate", "incubation.actualDate": "Petsa ng pagpisa", "incubation.unhatched": "Hindi napisa", "incubation.removed": "Tinanggal o sira", "incubation.accounted": "itlog ang accounted", "incubation.saveResults": "I-save ang hatch results", "incubation.createBatch": "Gumawa ng batch mula sa hatch",
    "settings.title": "Settings", "settings.preferences": "Language at itsura", "settings.language": "Language", "settings.appearance": "Itsura", "settings.light": "Light", "settings.dark": "Dark", "settings.preferencesDescription": "Piliin ang language at screen style na gusto mo.",
    "status.validation": "Validation workspace", "status.synthetic": "Synthetic data lang",
  },
} as const;

export type TranslationKey = keyof typeof messages.en;

export function getMessage(language: Language, key: TranslationKey) {
  return messages[language][key] ?? messages.en[key];
}
