"use client";

import { Activity, BarChart3, CheckCircle2, Egg, WalletCards } from "lucide-react";
import { useOperationsAnalytics } from "@/hooks/use-operations";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

function Metric({ icon: Icon, label, value, hint }: { icon: typeof Activity; label: string; value: string | number; hint: string }) { return <div className="rounded-xl border p-4"><Icon className="size-5 text-primary" /><p className="mt-3 text-xs text-muted-foreground">{label}</p><p className="text-2xl font-bold">{value}</p><p className="text-xs text-muted-foreground">{hint}</p></div>; }
export default function OperationsPage() {
  const { data, isLoading, isError } = useOperationsAnalytics();
  const hatchRate = data && data.incubation.eggsLoaded > 0 ? `${data.incubation.hatchRatePercent}%` : "No records";
  const taskRate = data && data.tasks.totalTasks > 0 ? `${data.tasks.completionRatePercent}%` : "No records";
  const net = data && data.finance.transactionCount > 0 ? `₱${Number(data.finance.net).toLocaleString()}` : "No records";
  return <div className="mx-auto w-full max-w-5xl space-y-6"><div><h1 className="text-3xl font-bold tracking-tight">Operations analytics</h1><p className="text-sm text-muted-foreground">Descriptive summaries from recorded farm operations. These are not predictions or diagnoses.</p></div>{isLoading && <p className="text-sm text-muted-foreground">Computing summaries…</p>}{isError && <p className="text-sm text-red-600">Analytics are not available yet. Add some records first.</p>}{data && <><p className="text-xs text-muted-foreground">Period: {data.startDate} to {data.endDate}</p><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Egg} label="Egg hatch rate" value={hatchRate} hint={data.incubation.eggsLoaded > 0 ? `${data.incubation.hatched} hatched of ${data.incubation.eggsLoaded} eggs` : "No incubation records in this period"} /><Metric icon={CheckCircle2} label="Task completion" value={taskRate} hint={data.tasks.totalTasks > 0 ? `${data.tasks.overdueTasks} overdue` : "No task records in this period"} /><Metric icon={Activity} label="Input logs" value={data.inputs.totalLogs || "No records"} hint="Feed, vitamins, medicine, vaccines" /><Metric icon={WalletCards} label="Recorded net" value={net} hint={`${data.finance.transactionCount} recorded transactions`} /></div><Card><CardHeader><CardTitle><BarChart3 className="mr-2 inline size-5" />What the numbers mean</CardTitle><CardDescription>Every result is traceable to recorded operations in the selected period.</CardDescription></CardHeader><CardContent className="grid gap-3 text-sm sm:grid-cols-2"><p>Completed incubation cycles: <b>{data.incubation.completedCycles || "No records"}</b></p><p>Average hatch duration: <b>{data.incubation.completedCycles > 0 ? `${data.incubation.averageDurationDays} days` : "No records"}</b></p><p>Open tasks: <b>{data.tasks.openTasks || "No records"}</b></p><p>Expenses: <b>{data.finance.transactionCount > 0 ? `₱${Number(data.finance.expense).toLocaleString()}` : "No records"}</b></p></CardContent></Card></>}</div>;
}
